{{- if .Values.serviceAccount.create -}}
{{- $saName := default "default" $.Values.serviceAccount.name }}
{{- if $.Values.serviceAccount.name }}
{{ $saName := $.Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $.Values.namespace | default "ssuman2" }}
  labels:
    {{- include "simple-nginx.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
